# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 366
        operations-per-run: 300
        stale-issue-message: 'This issue is over a year old and has been marked as stale. It will closed in 7 days if there is no activity.'
        close-issue-message: 'This issue has been closed due to lack of activity.'
        stale-pr-message: 'This pull request is over a year old and has been marked as stale. It will closed in 7 days if there is no activity.'
        close-pr-message: 'This pull request has been closed due to lack of activity.'
        stale-issue-label: 'stale-issue'
        stale-pr-label: 'stale-pr'
